name: update-flake-lock
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '0 3 * * 6' # Every Saturday morning

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7.0.1
      - name: Install Determinate Nix
        uses: DeterminateSystems/determinate-nix-action@v3.21.9
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@main
        with:
          token: ${{ secrets.UPDATE_LOCK }}
      - name: Commit to repository
        uses: stefanzweifel/git-auto-commit-action@v7.2.0
        with:
          branch: main
