name: Update flake.lock

on:
  schedule:
    - cron: "0 0 * * 3,6" # wednesday and saturday
  workflow_dispatch: # allows manual triggering

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_CLIENT_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}

      - uses: cachix/install-nix-action@v31

      - uses: mic92/update-flake-inputs@main
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          auto-merge: true
          auto-merge-method: REBASE