name: Update flake.lock

on:
  schedule:
    - cron: "0 0 * * 3,6" # wednesday and saturday
  workflow_dispatch: # allows manual triggering

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7.0.1

      - uses: DeterminateSystems/determinate-nix-action@v3.21.9

      - name: Update flake
        run: nix flake update

      - name: Check flake
        run: nix flake check

      - name: Check flake inputs
        uses: DeterminateSystems/flake-checker-action@v14

      - uses: stefanzweifel/git-auto-commit-action@v7.2.0
        with:
          file_pattern: flake.lock
          commit_message: flake.lock regular update
